[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "olefile>=0.47",
    "beautifulsoup4>=4.12.0",
    "streamlit>=1.51.0",
]

[tool.poetry]
package-mode = false
